# 2차원 배열의 리스트값 입력받고, 행과 열의 합을 구한 후, 행과 열을 추가하는 프로그램 작성

In [1]:
import numpy as np


In [10]:
row,col = 3,4
li = [[i+1 + j*col for i in range(col)] for j in range(row)]
print(li)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [25]:
np1 = np.array(li)
print(np1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
col_sum = np.sum(np1, axis=0)## 3행만 남음
print(col_sum)
print()

np1 = np.row_stack((np1,col_sum))
print(np1)


[15 18 21 24]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [15 18 21 24]]


In [27]:
row_sum = np.sum(np1, axis=1)#4열만 남음
print(row_sum)
print()

np1 = np.column_stack((np1,row_sum))
print(np1)


[10 26 42 78]

[[ 1  2  3  4 10]
 [ 5  6  7  8 26]
 [ 9 10 11 12 42]
 [15 18 21 24 78]]


In [42]:
# 채워넣는 다른 방법
# print("행 : ",np1.shape[0])
# print("열 : ",np1.shape[1])

np1 = np.array(li)
np2 = np.zeros((np1.shape[0]+1, np1.shape[1]+1))#  np.shape[0] 하면 row의 길이 나옴



In [44]:
np2[:-1, :-1] = np1
print(np2)
print()

np2[-1,:] = np.sum(np2,axis=0)
np2[:,-1] = np.sum(np2,axis=1)
print(np2)

[[ 1.  2.  3.  4.  0.]
 [ 5.  6.  7.  8.  0.]
 [ 9. 10. 11. 12.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  2.  3.  4. 10.]
 [ 5.  6.  7.  8. 26.]
 [ 9. 10. 11. 12. 42.]
 [15. 18. 21. 24. 78.]]


In [43]:
np1 = np.array(li)
np2 = np.zeros(np1.shape[0]+1, np1.shape[1]+1)


TypeError: ignored

행 :  4
열 :  3
