#문제1
리스트 [1,2,3,4,5]을 정의하고 각 원소에 곱하기 3을 수행한 새로운 리스트를 만드시오. 결과)[3,6,9,12,15]

step1 : index이용

step2 : 내장함수 이용

step3 : 함수화

step4 : List Comprehenseion

step5 : 데이터타입 변환(numpy모듈)

step6 : Map & Filter (Map 크기변화 x, Filter 크기변화 o)



abs ( 절댓값 )

divmod ( 나누기 )

enumerate -> 순서가 있는 자료형 ( 리스트 , 튜플 , 문자열 ) 을 입력받아 인덱스 값을 포함하는 enumerate 객체를 돌려준다.

eval

filter -> 결과를 true 또는 false로 반환하며, true의 원소만 가진 리스트 생성 

map -> 원소를 받아 함수 수행 후 , 결과값을 반환. 새로운 리스트 생성

max ( 최대값 )

min ( 최소값 )

pow ( 제곱 )

round ( 반올림 )

zip ( 동일한 개수로 묶어줌 )

all -> 모두 참이면 True, 거짓이 하나라도 있으면 False를 돌려

any ->  all(x)의 반대

chr

dir -> 객체가 자체적으로 가지고 있는 변수나 함수를 보여 준다

hex -> 정수값을 16진수로 변환하여 돌려줌 

oct -> 정수를 8진수 문자열로 바꿔주는 함수 

input -> 사용자 입력 받는 함수 

int -> 문자나 실수를 입력받아 정수로 돌려준다. 

isinstance

len

list -> 반복가능한 자료형을 입력받아 리스트로 만들어 돌려주는 함수 

range -> 입력받은 숫자에 해당하는 범위 값을 반복 가능한 객체로 만듬 

round -> 반올림 해주는 함수 

sorted -> 정렬한 후 그 결과를 리스트로 돌려줌

str -> 문자열로 바꾸어 돌려줌

sum -> 모든 요소의 합을 돌려줌 

tuple -> >>> tuple("abc")  -> ('a', 'b', 'c')





In [2]:
import numpy as np


> 디버깅 : 메모리의 변화를 관찰하는 작업

In [ ]:
# step 1
li = [1,2,3,4,5]
li_a = list(range(len(li)))
li_b = [0,0,0,0,0]
cnt =0

for i in range(5):
  li_a[i] = (li[i]*3)

for i in li:
  li_b[cnt] = (i*3)
  cnt = cnt + 1

print(li_a)
print(li_b)

[3, 6, 9, 12, 15]
[3, 6, 9, 12, 15]


In [ ]:
# step 1의 다른방법 (인덱스 이용)
li = [1,2,3,4,5]
li_a = list(range(len(li)))# malloc c언어 -> 메모리를 확보한다. 

for i,k in enumerate(li):# enumerate : 인덱스 위치와 값을  가져온다. (2개의 값을 돌려준다)
  # print("i= ", i) # 인덱스 위치 
  # print("k= ", k) # 해당 인덱스 값 
  li_a[i] = li[i]*3 # vectorization
  # print(i,k)
print(li_a)

[3, 6, 9, 12, 15]


In [ ]:
# step 2 (내장함수 이용)
li = [1,2,3,4,5]
li_a = []

for i in range(5):
  li_a.append(li[i]*3)

print(li_a)

[3, 6, 9, 12, 15]


In [ ]:
# step 3 (함수화)
li = [1,2,3,4,5]
li_a = [0,0,0,0,0]


def mul(li):
  for i in range(5):
    li_a[i] = (li[i]*3)
  return li_a
  
print(mul(li))

[3, 6, 9, 12, 15]


In [ ]:
# step 4 (List Compregension)
# 리스트 컴프리헨션은 쉽게 말해 ‘리스트를 쉽게, 짧게 한 줄로 만들 수 있는 파이썬의 문법’이다
# 장점
# 코드가 간결하다.
# 데이터베이스를 조회하여 리스트를 만들 때 많이 사용되므로, 새로운 배열을 만들때 특히 유용하다.
# 반복문을 활용하여 새로운 배열을 만드는것 보다 처리속도가 빠르다.
#단점 :복잡한 표현이 작성될 수록 가독성이 떨어진다.

li = [i for i in range(1,6)]
print(li)

li_a = []
li_a = [ i*3 for i in li]
print(li_a)

[1, 2, 3, 4, 5]
[3, 6, 9, 12, 15]


In [8]:
# step 5 (numpy로 데이터 타입변환  )
# numpy의 특징은 다음과 같습니다.
# 일반 List에 비해 빠르고, 메모리를 효율적으로 사용한다.
# 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리하다.
# 선형대수와 관련된 다양한 기능을 제공한다.
# C, C++, 포트란 등의 언어와 통합이 가능하다.

li = [1,2,3,4,5]
li_a = []
li_a = np.array(li)
print(li_a*3)

li_b = np.array(li)
li_b = li_b % 2 == 0
print(li_b)

[ 3  6  9 12 15]
[False  True False  True False]


In [ ]:
# step 6 (Map & Filter)

# Map
# map은 리스트의 요소를 지정된 함수로 처리해주는 함수입니다(map은 원본 리스트를 변경하지 않고 새 리스트를 생성)
# 여러 개의 데이터를 한 번에 다른 형태로 변환하기 위해서 사용된다. 
# 더 간단하고 메모리도 절약할 수 있는 iterator를 결과로 받을 수 있습니다.

# list(map(함수, 리스트))
# tuple(map(함수, 튜플))

def li_mul(num):
  return num * 3


li = [1,2,3,4,5]
li_a = []

# 꼭 list,tuple 형태로 map 사용해야함 
li_a = list(map(li_mul,li)) # 함수와 함께 사용 -> 반복적으로 함수 적용 후 결과 누적 
# li_a = list(map(lambda x: x*3, li)) # 같은 결과임 

print(li_a)



# Filter
# 함수의 조건에 일치하는 값만 반환하고 싶을 때 사용
# filter함수는 특정 조건으로 걸러서 걸러진 요소들로 iterator객체를 만들어서 리턴해줍니다
# map함수와 사용 방법은 동일하나, 함수의 결과가 참인지 거짓인지에 따라, 해당 요소를 포함할지를 결정합니다.
# 결과가 true 인 것만 여과한다. 


def li_mul_filter(num): # 결과를 true false로만 리턴함 
  # return True if num > 3 else False # 3이상의 숫자만 여과함 -> 결과 4,5 출력
  return True if type(num) == int or type(num) == float else False

li_a = []
li_a = list(filter(li_mul_filter,li)) #True 와 False 로 값이 출력된다.
li_a = np.array(li_a)

# li_a = list(filter(lambda x: x < 3, li)) # 3 이하의 값만 리턴

print(li_a*3)


[3, 6, 9, 12, 15]
[ 3  6  9 12 15]


# 문제2
리스트[1,2,3,4,5]을 정의하고 각 원소에 곱하기 3을 수행한 새로운 리스트를 만드시오. 단, 계산 결과가 짝수이면 0으로 치환해서 새로운 리스트를 만드시오

결과) [3,0,9,15]


In [ ]:
# step1 (index 이용)

li = [1,2,3,4,5]
li_a = []
cnt = 0

for i in range(0,5):
  li_a.append(li[i]*3)

for i in li_a:
  if i % 2 == 0:
    li_a[cnt] = 0
  cnt = cnt + 1

print(li_a)

[3, 0, 9, 0, 15]


In [ ]:
# step2 (내장함수 이용 )
# insert는 원하는 위치에 값 넣기, append는 맨 끝에 값 넣기 
# remove : 지정한 값을 지워준다. 

li = [3,6,9,12,15]
li_a = li.copy()

for i in range(5):
  if li[i] % 2 == 0:
    li_a.remove(li[i])
    li_a.insert(i,0)

print(li_a)

  

[3, 0, 9, 0, 15]


In [ ]:
# step3 (함수화)
li = [3,6,9,12,15]
li_a = li.copy()

def change_num(li):
  for i in range(len(li)):
    if li_a[i] % 2 == 0:
      li_a[i] = 0
  return li_a


print(change_num(li_a))


[3, 0, 9, 0, 15]


In [ ]:
# step4 (List Comprehension)
li = [3,6,9,12,15]
li_a = li.copy()

li_idx = [i for i in range(5) if li_a[i] % 2  == 0] # 짝수인 인덱스를 저장하는 배열
print(li_idx)#짝수 인덱스를 가짐 

for i in range(5):
  for j in li_idx:
    if i == j:# 짝수 인덱스와 같은 인덱스라면 0을 넣어줌
      li_a[i] = 0

print(li_a)
  


[1, 3]
[3, 0, 9, 0, 15]


In [ ]:
# step5 (numpy로 데이터타입변환)
li = [3,6,9,12,15]
li_a = li.copy()

npa = np.array(li_a)
print(npa)

a = (npa%2 == 0)
print(a)
npa[a] = 0
print(npa)

# for i in range(len(npa)):
#   if npa[i] % 2==0:
#     npa[i] = 0

# print(npa)

[ 3  6  9 12 15]
[False  True False  True False]
[ 3  0  9  0 15]


In [ ]:
# step6 (Map & Filter)
li = [3,6,9,12,15]
li_a = li.copy()

# Map
def change_num(num):
  if num % 2 == 0:
    return 0
  return num

li_a = list(map(change_num,li_a))
print(li_a)
print()


# Filter
li = [3,6,9,12,15]
li_a = li.copy()
li_filter = []

def filter_num(num):

  if num % 2 == 0:
    li_filter.append(0)
    return False
    
  li_filter.append(num)
  return True

li_a = list(filter(filter_num,li_a))
print(li_a)
print(li_filter)

# li_a = list(filter(filter_num,li_a))
# print(li_filter)

[3, 0, 9, 0, 15]

[3, 9, 15]
[3, 0, 9, 0, 15]
