In [2]:
import numpy as np
import math

# 9주차

In [ ]:
# 동전 나누기 

def calcoin(money):
  c500 = money // 500
  c100 = (money-(c500*500)) // 100
  c50 = (money-(c500*500)-(c100*100)) // 50
  return c500,c100,c50

# print(calcoin(7850))# 500*15 = 7500, 100*3=300, 50*1 = 50

print("500원: %d, 100원: %d, 50원: %d" % calcoin(7850))# 500*15 = 7500, 100*3=300, 50*1 = 50


500원: 15, 100원: 3, 50원: 1


In [ ]:
# 극좌표계(polor:각도와 반지름으로 구함 )와 직각좌표계(cart:x,y로출력)
# 극좌표계 각 40도, 반지름 10의 값을 직각좌표계로 출력
# 디그리(각도)를 라디안으로 바꾸는 것 
# 360' = 2*pi
# math.degrees(2 * pi) = 360'
# math.radians(360') = 2 * pi
# 라디안 = (디그리 / 180) * pi

def polor2cart(var):
  x = math.cos(math.radians(var[0])) * var[1]
  y = math.sin(math.radians(var[0])) * var[1]
  return x,y

pcl = (40,10)
print(polor2cart(pcl))

print("디그리(40')를 라디안으로 변경 : ",math.radians(40))
print("라디안(0.6981317007977318) 을 디그리로 변경 : ",math.degrees(0.6981317007977318))


# 앞의 수행을 딕셔너리를 이용해서 넘겨주기 
# 딕셔너리 = { 'key': value } 의 구조로 순서가 없다. 

def polor2cart2(var):
  x = math.cos(math.radians(var['theta'])) * var['r']
  y = math.sin(math.radians(var['theta'])) * var['r']
  return x,y

pcl = {'theta':40, 'r':10}
print(polor2cart2(pcl))

(7.66044443118978, 6.4278760968653925)
디그리(40')를 라디안으로 변경 :  0.6981317007977318
라디안(0.6981317007977318) 을 디그리로 변경 :  40.0
(7.66044443118978, 6.4278760968653925)


In [ ]:
# 원기둥 표면적 넓이 구하기 

def calcylinderArea(rr,hh):
  ca = math.pi * math.pow(rr,2)# 원의 넓이
  cr = 2 * math.pi * rr#원의 둘래
  ra = cr * hh#사각형 넓이
  return (2*ca+ra)

print("원의 표면적: ",calcylinderArea(2,4))

원의 표면적:  75.39822368615503


# 10주차 (행렬시작)

In [ ]:
# 행렬
lta = [[1,2,3],[4,5,6]] #2행 2열
ltb = [[7],[8],[9]]
print("***리스트 형태***")
print(lta)
print(ltb)
print()

npa = np.array(lta)
npb = np.array(ltb)
print("***numpy형태***")
print(npa)
print(npb)



***리스트 형태***
[[1, 2, 3], [4, 5, 6]]
[[7], [8], [9]]

***numpy형태***
[[1 2 3]
 [4 5 6]]
[[7]
 [8]
 [9]]


In [ ]:
# 리스트 안의 type 구분하기 

def isNumber(v):
  if type(v) == int or type(v) == float:
    return True
  elif type(v) == list or type(v) == tuple: #형태가 리스트나 튜플이면 하나씩 꺼내서 type을 확인하는데, 그 확인값이 리스트 형태로 li에 들어감 
    li = [isNumber(i) for i in v]
    return True if all(li) else False
  else:
    return False #문자열일 경우 

print(isNumber([1,2]))
print(isNumber([1,2,'a']))

True
False


In [ ]:
# 리스트에 들어있는 값이 모두 같은지 비교 

def ltall(lt):
  lt2 = lt.copy()
  lt.pop(0) # 첫번째 원소 지움
  lt2.pop() # 마지막 원소 지움
  return lt == lt2
lt = [1,1,2,1,1]
print("앞뒤로 제거 후 비교 : ",ltall(lt))

# 좌우 반전 후 비교하기. 
#가운데를 기점으로 반전되기 때문에 홀수일 경우 lt에 들어있는 아무 수를 추가해서 짝수 만듬

def ltall2(lt):
  if len(lt) % 2 != 0:
    lt.append(lt[0])
    # lt.insert(0,lt[0])#0번째 인덱스에 lt[0]의 값을 넣어준다. 
  lt2 = lt.copy()
  lt2.reverse()
  return lt == lt2

lt = [1,1,2,1,1]
print("좌우 반전 후 비교: ",ltall2(lt))


앞뒤로 제거 후 비교 :  False
좌우 반전 후 비교:  False


In [ ]:
# 리스트 모양(행과 열)을 출력하는 함수

def lt_shape(lt):
  row = len(lt)
  col_in_row = [len(lt[i]) for i in range(row)]#각 행별 길이가 저장됨
  if ltall2(col_in_row): #결과가 true 이면 실행 
    col = col_in_row[0]
  return row,col

lt = [[1,2,3],[4,5,6]] # 2행 3열 
print(lt_shape(lt))

(2, 3)


# 11주차 (전치행렬)


In [ ]:
# 전치행렬 만들기 

def lt_trans(lt):
  row,col = lt_shape(lt)
  lt_a = []
  for i in range(col):
    temp = []
    for j in range(row):
      temp.append(lt[j][i])
    lt_a.append(temp)
  return lt_a

lt = [[1,2,3],[4,5,6]] # 2행 3열 
lt_transform = np.array(lt_trans(lt))
print(lt_transform) # 3행 2열로 변경 

# print(np.array(lt_trans(lt_transform))) #다시 해주면 2행 3열로 전환 

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 내적 구하기  -> 내적하기 위해서는 숫자여야 하며, 열과 행이 일치해야 한다. 

def lt_mul(lta,ltb): # 두 리스트를 곱해주는 함수 
  print("mul에 들어오는 리스트 : ",lta,ltb)
  lt3 = [lta[i] * ltb[i] for i in range(len(lta))]
  return lt3


def lt_dot(lta,ltb):
  if not isNumber(lta) or not isNumber(ltb):
    print("잘못된 리스트 형태입니다. 리스트를 다시 입력하세요 ")
    return False
  if lt_shape(lta)[1] != lt_shape(ltb)[0]: #리스트 주고 행,열을 리스트 형태로 반환받아, 앞에는 열만 뒤에는 행만 추출해서 비교 
    print("두 리스트의 열과 행이 다릅니다. 동일하게 설정하세요. ")
    return False
  # 내적시작
  ltc = []
  for i in lta:
    temp = []
    for j in lt_trans(ltb):
      temp.append(sum(lt_mul(i,j))) # 곱한값을 더해줌 
    ltc.append(temp)
  return ltc


lta = [[1,2],[3,4]] # 2행 2열
ltb = [[5],[6]] # 2행 1열

a_1 = lt_shape(lta) # 2행 2열이 리스트 형태로 나온다/
a_2 = lt_shape(lta)[1] #리스트 형태중 열만 추출 
print("lt_shape이 반환하는 형태 : ",a_1)
print("lt_shape의 1번째 인덱스 추출 : ",a_2)

print("내적수행: ",lt_dot(lta,ltb))

lt_shape이 반환하는 형태 :  (2, 2)
lt_shape의 1번째 인덱스 추출 :  2
mul에 들어오는 리스트 :  [1, 2] [5, 6]
mul에 들어오는 리스트 :  [3, 4] [5, 6]
내적수행:  [[17], [39]]


In [4]:
# 2차행렬 가운데 0으로 만드는 문제 

row, col = 3,4

li = [[((i+1) + (j*col)) for i in range(col)] for j in range(row)] # 반복문 이용해서 숫자 만들기 
npa = np.array(li)
npa_copy = npa.copy()
print(npa)
print()

# 1. 슬라이싱 이용
npa_copy = npa.copy()
npa_copy[1:-1,1:-1] = 0
print(npa_copy)
print("###################")
print()


# 2. 인덱스 ones 이용
npa_copy = npa.copy()
idx = np.ones(shape=(row,col),dtype=bool)
print(idx)
print()

idx[0,:] = False
idx[:,0] = False
idx[:,-1] = False
idx[-1,:] = False
print(idx)
print()

npa_copy[idx] = 0
print(npa_copy)
print("###################")
print()

# 3. 인덱스 zeros 이용
npa_copy = npa.copy()
idx = np.zeros(shape=(3,4),dtype=bool)
print(idx)
print()

idx[1:-1,1:-1] = True
print(idx)
print()

npa_copy[idx] = 0
print(npa_copy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9 10 11 12]]
###################

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]

[[False False False False]
 [False  True  True False]
 [False False False False]]

[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9 10 11 12]]
###################

[[False False False False]
 [False False False False]
 [False False False False]]

[[False False False False]
 [False  True  True False]
 [False False False False]]

[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9 10 11 12]]


In [5]:
# i = 행에 속해있는 값을 만드는것
# j = 다음행이 어떤값을 가지게 할 지 만드는 것 
li = [[((i+1) + (j*col)) for i in range(col)] for j in range(row)] # 반복문 이용해서 숫자 만들기 
print(li)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


# 12주차


In [ ]:
# 2차원 리스트 입력받아 상하좌우와 테두리에 행과 열을 추가하는 리스트 만들기 (numpy사용)
row,col = 3,4
li = [[(i+1 + j*col) for i in range(col)] for j in range(row)]
np1 = np.array(li)
np1_copy = np1.copy()
print(np1)
print(np1.shape[0])
print(np1.shape[1])
print(np1.shape)
print()
# 1.부분 복사 방법

np2 = np.zeros(shape=(np1.shape[0]+2 , np1.shape[1]+2))
print(np2)
print()

np2[1:-1,1:-1] = np1
print(np2)
print()

np2[0,:] = np2[1]
np2[-1,:] = np2[-2]
print(np2)
print()

np2[:,0] = np2[:,1]
np2[:,-1] = np2[:,-2]
print(np2)
print("###############")
print()


# 2.행렬 결합방법 
np1_copy = np1.copy()
print(np1_copy)
print()

np1_copy = np.column_stack((np1_copy[:,0],np1_copy)) # 좌측 붙이기 
np1_copy = np.column_stack((np1_copy,np1_copy[:,-1]))# 우측붙이기 -> 순서 중요
print(np1_copy)
print()

np1_copy = np.row_stack((np1_copy[0,:],np1_copy))
np1_copy = np.row_stack((np1_copy,np1_copy[-1,:]))
print(np1_copy)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
3
4
(3, 4)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0.  0.  0.  0.  0.  0.]]

[[ 0.  1.  2.  3.  4.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0.  9. 10. 11. 12.  0.]]

[[ 1.  1.  2.  3.  4.  4.]
 [ 1.  1.  2.  3.  4.  4.]
 [ 5.  5.  6.  7.  8.  8.]
 [ 9.  9. 10. 11. 12. 12.]
 [ 9.  9. 10. 11. 12. 12.]]
###############

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  1  2  3  4  4]
 [ 5  5  6  7  8  8]
 [ 9  9 10 11 12 12]]

[[ 1  1  2  3  4  4]
 [ 1  1  2  3  4  4]
 [ 5  5  6  7  8  8]
 [ 9  9 10 11 12 12]
 [ 9  9 10 11 12 12]]


In [ ]:
# 2차원 행렬 입력받고 시계방향으로의 값을 가지는 리스트 만들기 , 최종적으로 리스트 합 구하기 

# 1. extend 이용
# extend = 리스트 형태 벗기고, 일차원의 리스트로 숫자들만 가져옴 (숫자쌓기 유리)
# append = 리스트 형태로 가져와서 차수도 같아짐 

row,col = 3,4
li = [[(i+1 + j*col) for i in range(col)] for j in range(row)]
np1 = np.array(li)
np1_copy = np1.copy()
print(np1)
print()


lt2 = []
lt2.extend(np1[0])#1,2,3,4 가져옴
print(lt2)
lt2.extend(np1[1:-1,-1]) # 8가져옴
print(lt2)
lt2.extend(np1[-1,::-1]) # 거꾸로해서 12,11,10,9로 값 가져옴
print(lt2)
lt2.extend(np1[1:-1,0]) # 5 가져옴
print(lt2)

# 2. append 이용

temp = np.array([]) # numpy의 array형태 
lt2 = [] #리스트 형태
print(type(temp))
print(type(lt2))


temp = np.append(temp,np1[0])#1,2,3,4 가져옴
print(temp)
temp = np.append(temp,np1[1:-1,-1]) # 8가져옴
print(temp)
temp = np.append(temp,np1[-1,::-1]) # 12,11,10,9 가져옴
print(temp)
temp = np.append(temp,np1[1:-1,0]) # 5가져옴
print(temp)

print(sum(temp))
print()

# numpy.array 의 형태는 append 자체적으로 사용 못함. 사용하기 위해서는 위의 방법을 이용해야함. 
# temp가 list 형태였다면 lt2.append 사용 가능했을것임 -> 하지만 append 형태로 가져오게 되면 차수도 가져오기 때문에 숫자 결합 이상해짐 
lt2.append(np1[0])
print(lt2)
lt2.append(np1[1:-1,-1])
print(lt2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1, 2, 3, 4]
[1, 2, 3, 4, 8]
[1, 2, 3, 4, 8, 12, 11, 10, 9]
[1, 2, 3, 4, 8, 12, 11, 10, 9, 5]
<class 'numpy.ndarray'>
<class 'list'>
[1. 2. 3. 4.]
[1. 2. 3. 4. 8.]
[ 1.  2.  3.  4.  8. 12. 11. 10.  9.]
[ 1.  2.  3.  4.  8. 12. 11. 10.  9.  5.]
65.0

[array([1, 2, 3, 4])]
[array([1, 2, 3, 4]), array([8])]


# 13주차


In [ ]:
# 2차원 배열의 리스트 값 입력받고, 행과 열의 합을 구한 후 , 행과 열을 추가하는 프로그램 작성

row,col = 3,4
li = [[(i+1 + j*col) for i in range(col)] for j in range(row)]
np1 = np.array(li)
print(np1)

print("행의 합 출력: ",sum(np1)) # 내장함수 이용
print("전체 합 출력: ",np.sum(np1)) # 외장함수 이용해서 전체합 구하기
print("행과 열 지정후 합 출력: ", np.sum(np1,axis=0)) # 외장함수 이용해 행의 합 구하기 
print()

# 1. 행,열별로 합 구하기 
col_sum = np.sum(np1,axis=1)
print(col_sum)
print()

np1 = np.column_stack((np1,col_sum)) # 이중괄호 조심하기
print(np1)
print()

row_sum = np.sum(np1,axis=0)
print(row_sum)
print()

np1 = np.row_stack((np1,row_sum))
print(np1)
print()
print("####################")

# 2. 행렬 만들고 추가하기 (복사 이용)\
np1 = np.array(li)
np2 = np.zeros(shape=(4,5)) # 행렬의 합이 들어가야 하기 때문에 1행1열 늘려줌 
print(np2)
print()

np2[0:-1,0:-1] = np1
print(np2)
print()

np2[:,-1] = np.sum(np2,axis=1)
np2[-1,:] = np.sum(np2,axis=0)
print(np2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
행의 합 출력:  [15 18 21 24]
전체 합 출력:  78
행과 열 지정후 합 출력:  [15 18 21 24]

[10 26 42]

[[ 1  2  3  4 10]
 [ 5  6  7  8 26]
 [ 9 10 11 12 42]]

[15 18 21 24 78]

[[ 1  2  3  4 10]
 [ 5  6  7  8 26]
 [ 9 10 11 12 42]
 [15 18 21 24 78]]

####################
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[ 1.  2.  3.  4.  0.]
 [ 5.  6.  7.  8.  0.]
 [ 9. 10. 11. 12.  0.]
 [ 0.  0.  0.  0.  0.]]

[[ 1.  2.  3.  4. 10.]
 [ 5.  6.  7.  8. 26.]
 [ 9. 10. 11. 12. 42.]
 [15. 18. 21. 24. 78.]]
