In [1]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd


In [2]:
#데이터 준비
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
#결과가 범주형(이름) 이기 때문에 확률 계산하기 위해서 원핫인코딩 사용
#원핫인코딩 = 결과를 0과 1의 확률로 바꿔줌

아이리스 = pd.get_dummies(아이리스)
print(아이리스.columns)

아이리스.head()


Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [5]:
#종속변수(결과)와 독립변수(원인) 나눠주기

종속 = 아이리스[['품종_setosa', '품종_versicolor','품종_virginica']]
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]

print(종속.shape,독립.shape)



(150, 3) (150, 4)


In [6]:
#모델 생성

x = tf.keras.layers.Input(shape = 4)
#softmax함수를 이용해 결과를 퍼센트로 나타내줌
y = tf.keras.layers.Dense(3,activation='softmax')(x)


model = tf.keras.models.Model(x,y)
#결과가 양적(숫자)라면 mse, 결과가 범주(이름)이라면 crossentropy를 사용한다.
model.compile(loss='categorical_crossentropy',metrics='accuracy')


In [7]:
#모델을 학습시킨다.
model.fit(독립,종속,epochs=1000,verbose=0)
model.fit(독립,종속,epochs=10)


Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1527 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1524 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1525 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1527 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1527 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1519 - accuracy: 0.9733
Epoch 7/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1521 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1520 - accuracy: 0.9733
Epoch 9/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1523 - accuracy: 0.9733
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1520 - accuracy: 0.9733


In [8]:
#모델을 사용해본다
#뒤에서 5번째부터 맨뒤까지 숫자를 이용
print(model.predict(독립[-5:]))


[[3.5198454e-07 1.1587124e-01 8.8412833e-01]
 [1.0538186e-06 1.9983731e-01 8.0016160e-01]
 [2.1735332e-06 2.1731760e-01 7.8268027e-01]
 [4.4554230e-07 6.3315734e-02 9.3668383e-01]
 [6.7735582e-06 2.1622655e-01 7.8376669e-01]]


In [10]:
#모델을 사용해 나온 결과와 정답비교

print(model.predict(독립[-5:]))
print("")
print(종속[-5:])

[[3.5198454e-07 1.1587124e-01 8.8412833e-01]
 [1.0538186e-06 1.9983731e-01 8.0016160e-01]
 [2.1735332e-06 2.1731760e-01 7.8268027e-01]
 [4.4554230e-07 6.3315734e-02 9.3668383e-01]
 [6.7735582e-06 2.1622655e-01 7.8376669e-01]]

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [11]:
# weights & bias 출력
print(model.get_weights())

[array([[ 0.1547105 ,  0.34268987, -1.1066612 ],
       [ 3.8589509 ,  0.69602346, -0.3076311 ],
       [-3.0603771 , -0.46483102,  1.2295448 ],
       [-4.5208464 , -0.6740262 ,  2.7947352 ]], dtype=float32), array([ 2.0776126,  0.666811 , -1.3683555], dtype=float32)]
